Locales ['en'] = {
	['judge'] = 'A-TEAM',
	['escape_attempt'] = 'You can´t escape. Your sentence has been increased.',
	['remaining_msg'] = 'You have ~b~%s~s~ more actions to complete before you finish your punishment.',
	['comserv_msg'] = '%s received a penalty of %s Penalty Points for %s.',
	['comserv_finished'] = '%s finished his sentence!',
	['press_to_start'] = 'Press ~g~E~s~ to start.',
	['system_msn'] = '^1SYSTEM',
	['invalid_player_id_or_actions'] = 'Invalid player ID or number of actions.',
	['insufficient_permissions'] = 'Insufficient permissions.',
	['give_player_community'] = 'Give the players a penalty',
	['target_id'] = 'Player ID',
	['action_count_suggested'] = 'Number of points [recommended: 1-150]',
	['reason'] = 'Důvod',
	['invalid_player_id'] = 'Invalid player ID!',
	['unjail_people'] = 'The punishment was withdrawn.',
	['discord_log'] = "received a penalty of **%s** Penalty Points due to: **%s**",
	['discord_log_name'] = "Penalty points - Logger",
}

Locales ['cs'] = {
	['judge'] = 'A-TEAM',
	['escape_attempt'] = 'Nemůžeš uniknout. Váš trest byl navýšen.',
	['remaining_msg'] = 'Máte ~b~%s~s~ ještě než dokončíte trest, musíte dokončit další akce.',
	['comserv_msg'] = '%s obdržel trest ve výši %s Trestných bodu za %s.',
	['comserv_finished'] = '%s dokončil svůj trest!',
	['press_to_start'] = 'Stiskni ~g~E~s~ pro spuštění.',
	['system_msn'] = '^1SYSTEM',
	['invalid_player_id_or_actions'] = 'Neplatné ID hráče nebo počet akcí.',
	['insufficient_permissions'] = 'Nedostatečná oprávnění.',
	['give_player_community'] = 'Dejte hráčům trest',
	['target_id'] = 'ID hráře',
	['action_count_suggested'] = 'Počet akcí [doporučeno: 1-150]',
	['reason'] = 'Důvod',
	['invalid_player_id'] = 'Neplatné ID hráče!',
	['unjail_people'] = 'Trest byl stáhnut.',
	['discord_log'] = "obdržel trest ve výši **%s** Trestných bodů z důvodu: **%s**",
	['discord_log_name'] = "Trestné body - Logger",
}

Locales ['other'] = {
	['judge'] = 'A-TEAM',
	['escape_attempt'] = 'You can´t escape. Your sentence has been increased.',
	['remaining_msg'] = 'You have ~b~%s~s~ more actions to complete before you finish your punishment.',
	['comserv_msg'] = '%s received a penalty of %s Penalty Points for %s.',
	['comserv_finished'] = '%s finished his sentence!',
	['press_to_start'] = 'Press ~g~E~s~ to start.',
	['system_msn'] = '^1SYSTEM',
	['invalid_player_id_or_actions'] = 'Invalid player ID or number of actions.',
	['insufficient_permissions'] = 'Insufficient permissions.',
	['give_player_community'] = 'Give the players a penalty',
	['target_id'] = 'Player ID',
	['action_count_suggested'] = 'Number of points [recommended: 1-150]',
	['reason'] = 'Důvod',
	['invalid_player_id'] = 'Invalid player ID!',
	['unjail_people'] = 'The punishment was withdrawn.',
	['discord_log'] = "received a penalty of **%s** Penalty Points due to: **%s**",
	['discord_log_name'] = "Penalty points - Logger",
}

